version: '2'
services:
  stanza:
    build: .
    image: registry.gitlab.com/sparqlite/noguchi/glycosite/stanza/rb:0.01
    command: /usr/local/bin/bundle exec rackup -p 80
#    command: /usr/local/bundle/bin/bundle exec rake rails:update:bin -p 80
    ports:
      - 9292:80
    volumes: 
      - ../glytoucan-stanza:/app/glytoucan-stanza
      - /etc/localtime:/etc/localtime
    working_dir: /app/glytoucan-stanza
    restart: always
